import {StyleSheet} from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  contentFrame: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 393,
    alignSelf: 'center',
    paddingTop: 19,
    paddingBottom: 30,
    justifyContent: 'space-between',
  },
  mainContent: {
    width: '100%',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  backdropTopHighlight: {
    position: 'absolute',
    top: -22,
    right: 38,
    width: 126,
    height: 126,
    borderRadius: 63,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  backdropOrbSecondary: {
    position: 'absolute',
    top: 548,
    right: -118,
    width: 286,
    height: 286,
    borderRadius: 143,
    backgroundColor: 'rgba(214,221,234,0.56)',
  },
  backdropOrbTertiary: {
    position: 'absolute',
    bottom: -64,
    left: -54,
    width: 232,
    height: 232,
    borderRadius: 116,
    backgroundColor: 'rgba(223,227,236,0.72)',
  },
  header: {
    width: '100%',
    minHeight: 33,
    paddingLeft: 13,
    paddingRight: 15,
    zIndex: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sourceButton: {
    minWidth: 74,
    maxWidth: 148,
    height: 29,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.86)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    shadowColor: '#bfc9d9',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 2,
  },
  sourceButtonActive: {
    backgroundColor: '#177cff',
    shadowColor: '#6faeff',
    shadowOpacity: 0.24,
  },
  sourceButtonPlus: {
    color: '#c4c4c4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    marginRight: 4,
  },
  sourceButtonText: {
    color: '#c4c4c4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    flexShrink: 1,
  },
  sourceButtonTextActive: {
    color: '#ffffff',
  },
  githubButton: {
    width: 33,
    height: 33,
    borderRadius: 16.5,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#bfc9d9',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 2,
  },
  accountButton: {
    width: 41,
    height: 41,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    elevation: 2,
  },
  accountAvatar: {
    width: 41,
    height: 41,
  },
  guestAccountButton: {
    width: 58,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#24a46b',
  },
  guestAccountText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  logoImage: {
    width: 99,
    height: 26,
  },
  heroSection: {
    width: '100%',
    minHeight: 170,
    zIndex: 4,
  },
  heroSectionCompact: {
    minHeight: 146,
  },
  heroStage: {
    width: '100%',
    minHeight: 170,
  },
  heroStageCompact: {
    minHeight: 146,
  },
  heroBrandWrap: {
    width: '100%',
    minHeight: 170,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingLeft: 29,
    paddingTop: 12,
    paddingRight: 36,
  },
  heroBrandWrapCompact: {
    minHeight: 146,
    paddingTop: 10,
    paddingRight: 30,
  },
  heroTitle: {
    width: 252,
    color: '#000000',
    fontSize: 26,
    lineHeight: 34,
    textAlign: 'left',
    fontWeight: '300',
    letterSpacing: 0,
    marginTop: 6,
  },
  heroTitleCompact: {
    width: 238,
    fontSize: 24,
    lineHeight: 31,
    marginTop: 5,
  },
  heroHighlight: {
    color: '#1c77eb',
    fontWeight: '500',
  },
  heroCreateWrap: {
    width: '100%',
    minHeight: 170,
    paddingTop: 28,
    paddingLeft: 31,
    paddingRight: 34,
    paddingBottom: 8,
    justifyContent: 'flex-start',
  },
  heroCreateWrapCompact: {
    minHeight: 146,
    paddingTop: 22,
    paddingRight: 28,
    paddingBottom: 6,
  },
  heroCreateTitle: {
    width: 252,
    color: '#000000',
    fontSize: 26,
    lineHeight: 34,
    textAlign: 'left',
    fontWeight: '300',
    marginBottom: 16,
  },
  heroCreateTitleCompact: {
    width: 238,
    fontSize: 24,
    lineHeight: 31,
    marginBottom: 12,
  },
  heroCreateLabel: {
    color: '#1c77eb',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '500',
    marginBottom: 10,
  },
  heroCreateLabelCompact: {
    marginBottom: 8,
  },
  heroLabelRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  heroLabelSpark: {
    position: 'relative',
    width: 18,
    height: 16,
    marginLeft: 3,
    marginTop: -2,
  },
  heroLabelSparkMain: {
    position: 'absolute',
    left: 0,
    top: 2,
    color: '#1c77eb',
    fontSize: 16,
    lineHeight: 16,
  },
  heroLabelSparkSmall: {
    position: 'absolute',
    right: 0,
    top: 0,
    color: '#1c77eb',
    fontSize: 8,
    lineHeight: 8,
    opacity: 0.86,
  },
  heroCreateBody: {
    width: '100%',
    maxWidth: 312,
    color: '#000000',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '500',
    letterSpacing: 0,
  },
  heroCreateBodyCompact: {
    maxWidth: 300,
    fontSize: 15,
    lineHeight: 21,
  },
  heroStrategyWrap: {
    width: '100%',
    minHeight: 170,
    paddingTop: 18,
    paddingLeft: 31,
    paddingRight: 34,
    paddingBottom: 8,
    justifyContent: 'flex-start',
  },
  heroStrategyWrapCompact: {
    minHeight: 146,
    paddingTop: 14,
    paddingRight: 28,
    paddingBottom: 6,
  },
  heroStrategyLabel: {
    color: '#1c77eb',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '500',
    marginBottom: 10,
  },
  heroStrategyLabelCompact: {
    marginBottom: 8,
  },
  heroStrategyBody: {
    width: '100%',
    maxWidth: 320,
    color: '#000000',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '500',
    letterSpacing: 0,
    flexShrink: 1,
  },
  heroStrategyBodyGroup: {
    width: '100%',
    maxWidth: 320,
    justifyContent: 'flex-start',
  },
  heroStrategyBodyGroupCompact: {
    maxWidth: 306,
  },
  heroStrategyParagraph: {
    marginBottom: 7,
  },
  heroStrategyBodyCompact: {
    maxWidth: 306,
    fontSize: 15,
    lineHeight: 21,
    flexShrink: 1,
  },
  feedbackSlot: {
    width: '100%',
    height: 4,
    marginTop: 0,
    justifyContent: 'center',
  },
  feedbackSlotCompact: {
    height: 0,
    marginTop: 0,
  },
  loadingSection: {
    width: '100%',
    alignItems: 'center',
    zIndex: 9,
  },
  loadingText: {
    color: '#6b7280',
    fontSize: 14,
  },
  errorSection: {
    width: '100%',
    paddingHorizontal: 24,
    alignItems: 'center',
    zIndex: 9,
  },
  errorText: {
    color: '#dc2626',
    fontSize: 14,
    textAlign: 'center',
  },
  deckCluster: {
    width: '100%',
    paddingLeft: 24,
    paddingRight: 23,
    alignItems: 'center',
    zIndex: 6,
    marginTop: -4,
  },
  deckInner: {
    width: '100%',
    alignItems: 'flex-start',
  },
  progressBadge: {
    width: 84,
    marginLeft: 9,
    marginBottom: 6,
    zIndex: 40,
    elevation: 40,
  },
  progressBadgeCompact: {
    marginBottom: 5,
  },
  progressText: {
    color: '#949494',
    fontSize: 10,
    lineHeight: 14,
    textAlign: 'left',
    fontWeight: '400',
  },
  deckSection: {
    width: '100%',
    height: 358,
    paddingTop: 4,
    justifyContent: 'flex-start',
    zIndex: 1,
  },
  deckSectionCompact: {
    height: 348,
    paddingTop: 3,
  },
  actionSection: {
    width: '100%',
    paddingLeft: 31,
    paddingRight: 43,
    zIndex: 8,
    alignItems: 'flex-start',
  },
  actionSectionCompact: {
    paddingLeft: 30,
    paddingRight: 38,
  },
  footerActionStage: {
    width: '100%',
    minHeight: 46,
    justifyContent: 'flex-start',
  },
  footerPreviewActionWrap: {
    width: 179,
  },
  footerCreateActions: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 3,
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerCreateActionsCompact: {
    top: 2,
  },
  footerActionGroupLeft: {
    height: 24,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  footerActionGroupRight: {
    height: 24,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  ctaShadow: {
    width: 179,
    borderRadius: 21,
    shadowColor: '#286fe7',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 3,
  },
  ctaShadowCompact: {
    width: 176,
  },
  ctaButton: {
    width: 179,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#286fe7',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaButtonIcon: {
    color: '#ffffff',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '300',
    marginRight: 8,
    marginTop: -1,
  },
  ctaButtonCompact: {
    width: 176,
    height: 40,
    borderRadius: 20,
  },
  ctaButtonText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
  },
  inlineActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 20,
  },
  inlineActionIconWrap: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  inlineActionText: {
    color: '#7d8591',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '600',
  },
  inlineCancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 20,
  },
  inlineCancelIconWrap: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  inlineCancelText: {
    color: '#111111',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '600',
  },
  disclaimerWrap: {
    width: '100%',
  },
  disclaimer: {
    width: 319,
    marginTop: 14,
    color: '#8d8d8d',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '300',
    textAlign: 'left',
  },
  disclaimerCompact: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 16,
  },
})
