import {StyleSheet} from 'react-native'
import {colors, radius, shadow, space, typography} from '@/styles/tokens'

export const styles = StyleSheet.create({
  step: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: space[9],
  },
  stepCompact: {
    paddingTop: space[1],
    paddingBottom: space[1],
  },
  stepFill: {
    flex: 1,
    minHeight: 0,
  },
  applicationCard: {
    position: 'relative',
    width: '100%',
    maxWidth: 330,
    alignSelf: 'center',
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.border.warmCard,
    backgroundColor: colors.surface.transparent,
    paddingTop: 25,
    paddingHorizontal: space[7],
    paddingBottom: space[8],
    ...shadow.warmCard,
  },
  applicationCardCompact: {
    maxWidth: 304,
    paddingTop: 24,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  applicationCardFill: {
    flex: 1,
    minHeight: 0,
  },
  cardSurface: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.card,
    overflow: 'hidden',
    backgroundColor: colors.surface.warmBase,
  },
  cardSurfaceCompact: {
    borderRadius: radius.card,
  },
  cardHardware: {
    position: 'absolute',
    top: 8,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 3,
  },
  island: {
    width: 88,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: 'rgba(170, 171, 178, 0.95)',
  },
  islandCompact: {
    width: 70,
    height: 6,
    backgroundColor: 'rgba(162, 165, 170, 0.82)',
  },
  ribbonRow: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'stretch',
    alignSelf: 'flex-start',
    marginLeft: -16,
    marginBottom: 14,
    ...shadow.ribbon,
  },
  ribbonRowCompact: {
    marginLeft: -14,
    marginTop: 2,
    marginBottom: 12,
  },
  ribbonFold: {
    position: 'absolute',
    left: 0,
    bottom: -5,
    width: 0,
    height: 0,
    borderTopWidth: 5,
    borderRightWidth: 7,
    borderTopColor: colors.brand.blueRibbonFold,
    borderRightColor: 'transparent',
  },
  ribbonFoldCompact: {
    bottom: -3,
    borderTopWidth: 3,
    borderRightWidth: 5,
  },
  ribbon: {
    justifyContent: 'center',
    minHeight: 27,
    backgroundColor: colors.brand.blueRibbon,
    paddingLeft: 13,
    paddingRight: 12,
    borderTopRightRadius: 7,
    borderBottomRightRadius: 7,
  },
  ribbonCompact: {
    minHeight: 20,
    paddingLeft: 8,
    paddingRight: 8,
  },
  ribbonTail: {
    width: 0,
    height: 0,
    borderTopWidth: 13.5,
    borderBottomWidth: 13.5,
    borderLeftWidth: 10,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: colors.brand.blueRibbon,
  },
  ribbonTailCompact: {
    borderTopWidth: 10,
    borderBottomWidth: 10,
    borderLeftWidth: 7,
  },
  ribbonText: {
    color: colors.text.inverse,
    fontSize: typography.fontSize.sm,
    lineHeight: 14,
    fontWeight: typography.weight.bold,
    letterSpacing: 0.2,
  },
  ribbonTextCompact: {
    fontSize: 9.5,
    lineHeight: 11,
  },
  fieldBlock: {
    marginBottom: 12,
  },
  fieldBlockCompact: {
    marginBottom: 6,
  },
  descriptionFieldFill: {
    flex: 1,
    minHeight: 0,
  },
  fieldLabel: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    lineHeight: typography.lineHeight.lg,
    fontWeight: typography.weight.bold,
    marginBottom: 7,
  },
  fieldLabelCompact: {
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 5,
  },
  inputShell: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.warmSoft,
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 16,
    minHeight: 46,
    justifyContent: 'center',
  },
  inputShellCompact: {
    minHeight: 40,
    paddingHorizontal: 10,
  },
  input: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.lg,
    lineHeight: typography.lineHeight.lg,
  },
  inputCompact: {
    fontSize: 14,
    lineHeight: 18,
  },
  jdPanel: {
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border.warmPanel,
    backgroundColor: colors.surface.warmPanel,
    overflow: 'hidden',
    minHeight: 228,
  },
  jdPanelCompact: {
    minHeight: 166,
  },
  jdPanelFill: {
    flex: 1,
    minHeight: 0,
  },
  uploadPanel: {
    minHeight: 182,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  uploadPanelCompact: {
    minHeight: 126,
    paddingVertical: 8,
  },
  uploadPanelFill: {
    flex: 1,
  },
  uploadIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: '#efe5df',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow.softWarm,
    marginBottom: 8,
  },
  uploadIconWrapCompact: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginBottom: 6,
  },
  uploadIconPlate: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fffdfa',
    borderWidth: 1,
    borderColor: '#ece1db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadIconPlateCompact: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  documentGlyph: {
    width: 30,
    height: 36,
    borderRadius: 8,
    borderWidth: 1.8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
  },
  documentGlyphCompact: {
    width: 22,
    height: 28,
    borderRadius: 6,
    paddingTop: 3,
  },
  documentGlyphMuted: {
    borderColor: colors.icon.documentMuted,
    backgroundColor: '#faf6f2',
  },
  documentGlyphAccent: {
    borderColor: colors.brand.warmDark,
    backgroundColor: '#fff6ef',
  },
  documentGlyphFold: {
    position: 'absolute',
    right: -2,
    top: -2,
    width: 10,
    height: 10,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    transform: [{rotate: '0deg'}],
  },
  documentGlyphFoldCompact: {
    width: 8,
    height: 8,
  },
  documentGlyphFoldMuted: {
    backgroundColor: colors.surface.white,
    borderColor: colors.icon.documentMuted,
  },
  documentGlyphFoldAccent: {
    backgroundColor: '#ffece1',
    borderColor: colors.brand.warmDark,
  },
  documentGlyphLineShort: {
    width: 12,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(198, 185, 178, 0.82)',
    marginBottom: 4,
  },
  documentGlyphLineLong: {
    width: 16,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(198, 185, 178, 0.82)',
    marginBottom: 4,
  },
  documentGlyphLineAccent: {
    backgroundColor: 'rgba(242, 123, 89, 0.62)',
  },
  uploadTitle: {
    color: '#d2c3bb',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
  },
  uploadTitleCompact: {
    color: '#c8b8b0',
    fontSize: 16,
    lineHeight: 20,
  },
  uploadSubtitle: {
    marginTop: 4,
    color: '#cdbeb6',
    fontSize: 11.5,
    lineHeight: 17,
    textAlign: 'center',
  },
  uploadSubtitleCompact: {
    marginTop: 3,
    color: '#c6b7af',
    fontSize: 10.5,
    lineHeight: 15,
  },
  loadingPanel: {
    minHeight: 182,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  loadingPanelCompact: {
    minHeight: 126,
    paddingVertical: 8,
  },
  loadingPanelFill: {
    flex: 1,
  },
  previewPanel: {
    position: 'relative',
    minHeight: 182,
    backgroundColor: '#f5ede9',
  },
  previewPanelCompact: {
    minHeight: 126,
  },
  previewPanelFill: {
    flex: 1,
    minHeight: 0,
  },
  previewImage: {
    width: '100%',
    height: 182,
  },
  previewImageCompact: {
    height: 126,
  },
  previewImageFill: {
    height: '100%',
  },
  previewImageMask: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  previewBadge: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 58,
    height: 58,
    marginLeft: -29,
    marginTop: -29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewBadgeRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: '#ff6c43',
  },
  previewBadgeInner: {
    width: 48,
    height: 48,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filePanel: {
    minHeight: 182,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  filePanelCompact: {
    minHeight: 126,
    paddingVertical: 8,
  },
  filePanelFill: {
    flex: 1,
  },
  filePanelIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#ff6c43',
    backgroundColor: 'rgba(255,255,255,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  filePanelIconCompact: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 12,
  },
  filePanelName: {
    color: '#6f625b',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    textAlign: 'center',
  },
  filePanelNameCompact: {
    fontSize: 14,
    lineHeight: 20,
  },
  filePanelMeta: {
    marginTop: 4,
    color: '#b2a49d',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  filePanelMetaCompact: {
    lineHeight: 17,
  },
  errorPanel: {
    minHeight: 182,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  errorPanelCompact: {
    minHeight: 126,
    paddingVertical: 8,
  },
  errorPanelFill: {
    flex: 1,
  },
  errorBadge: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 2,
    borderColor: colors.state.errorBorder,
    backgroundColor: colors.state.errorBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  errorBadgeCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginBottom: 12,
  },
  errorBadgeText: {
    color: colors.brand.warm,
    fontSize: typography.fontSize.badge,
    lineHeight: typography.lineHeight.badge,
    fontWeight: typography.weight.bold,
  },
  errorBadgeTextCompact: {
    fontSize: 24,
    lineHeight: 24,
  },
  errorTitle: {
    color: colors.state.errorText,
    fontSize: typography.fontSize.xl,
    lineHeight: typography.lineHeight.xl,
    fontWeight: typography.weight.bold,
  },
  errorTitleCompact: {
    fontSize: 15,
    lineHeight: 20,
  },
  errorSubtitle: {
    marginTop: 6,
    color: '#b7978e',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  errorSubtitleCompact: {
    marginTop: 4,
    lineHeight: 18,
  },
  textareaWrap: {
    minHeight: 182,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: colors.surface.warmPanelSoft,
  },
  textareaWrapCompact: {
    minHeight: 126,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 5,
  },
  textareaWrapFill: {
    flex: 1,
    minHeight: 0,
  },
  textarea: {
    minHeight: 160,
    color: colors.text.secondary,
    fontSize: typography.fontSize.xl,
    lineHeight: typography.lineHeight.body,
    textAlignVertical: 'top',
  },
  textareaCompact: {
    minHeight: 113,
    fontSize: 14,
    lineHeight: 20,
  },
  textareaFill: {
    flex: 1,
    minHeight: 0,
  },
  modeBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.border.warmSoftAlt,
    backgroundColor: 'rgba(255,248,243,0.84)',
    minHeight: 42,
  },
  modeBarDivider: {
    width: 1,
    backgroundColor: '#f2e7df',
  },
  modeTab: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeTabCompact: {
    minHeight: 36,
  },
  modeTabActive: {
    backgroundColor: colors.surface.warmTab,
  },
  modeTabGlyph: {
    color: colors.icon.muted,
    fontSize: 18,
    lineHeight: 18,
    fontWeight: '700',
  },
  modeTabGlyphActive: {
    color: colors.brand.warmDark,
    fontSize: 18,
    lineHeight: 18,
    fontWeight: '700',
  },
  pencilGlyph: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pencilGlyphBody: {
    width: 13,
    height: 2.4,
    borderRadius: radius.full,
    backgroundColor: colors.icon.muted,
    transform: [{rotate: '-34deg'}],
  },
  pencilGlyphBodyActive: {
    backgroundColor: colors.brand.warmDark,
  },
  pencilGlyphTip: {
    position: 'absolute',
    right: 2,
    top: 8,
    width: 5,
    height: 5,
    borderTopWidth: 1.8,
    borderRightWidth: 1.8,
    borderColor: colors.icon.muted,
    transform: [{rotate: '12deg'}],
  },
  pencilGlyphTipActive: {
    borderColor: colors.brand.warmDark,
  },
  modeTabUploadIcon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeTabUploadIconFrame: {
    width: 19,
    height: 17,
    borderWidth: 1.8,
    borderColor: colors.icon.muted,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  modeTabUploadIconFrameActive: {
    borderColor: colors.brand.warmDark,
  },
  modeTabUploadIconStem: {
    position: 'absolute',
    top: -9,
    width: 1.8,
    height: 11,
    backgroundColor: colors.icon.muted,
  },
  modeTabUploadIconStemActive: {
    backgroundColor: colors.brand.warmDark,
  },
  modeTabUploadIconArrow: {
    position: 'absolute',
    top: -9,
    width: 0,
    height: 0,
    borderLeftWidth: 5.5,
    borderRightWidth: 5.5,
    borderBottomWidth: 7.5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.icon.muted,
  },
  modeTabUploadIconArrowActive: {
    borderBottomColor: colors.brand.warmDark,
  },
  tipText: {
    width: '100%',
    maxWidth: 304,
    alignSelf: 'center',
    marginTop: 8,
    color: colors.text.muted,
    fontSize: 12.5,
    lineHeight: 18,
  },
  tipTextCompact: {
    marginTop: 6,
    fontSize: 11,
    lineHeight: 16,
  },
  tipTextFill: {
    marginTop: 6,
    alignSelf: 'center',
  },
})
