import {StyleSheet} from 'react-native'
import {colors, radius, space, typography} from '@/styles/tokens'

export const styles = StyleSheet.create({
  step: {
    paddingBottom: space[9],
  },
  section: {
    marginBottom: space[8],
  },
  sectionTitle: {
    color: '#131313',
    fontSize: 18,
    lineHeight: typography.lineHeight.body,
    fontWeight: typography.weight.bold,
    marginBottom: space[5],
  },
  uploadCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border.cool,
    backgroundColor: colors.surface.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadCardLarge: {
    minHeight: 136,
    paddingHorizontal: space[9],
    paddingVertical: space[10],
  },
  uploadHint: {
    marginTop: space[5],
    color: '#b8c5d4',
    fontSize: 17,
    lineHeight: typography.lineHeight.xl,
    fontWeight: typography.weight.semibold,
  },
  documentIcon: {
    position: 'relative',
    width: 36,
    height: 44,
    borderRadius: radius.xs,
    borderWidth: 2,
    borderColor: '#afc1d4',
    backgroundColor: '#f7fbff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  documentIconFilled: {
    borderWidth: 0,
    backgroundColor: '#177cff',
  },
  documentFold: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 12,
    height: 12,
    backgroundColor: colors.surface.white,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#afc1d4',
  },
  documentFoldFilled: {
    borderColor: '#177cff',
    backgroundColor: '#dcecff',
  },
  uploadArrow: {
    color: '#afc1d4',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: typography.weight.bold,
  },
  documentBadge: {
    color: colors.text.inverse,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: typography.weight.bold,
  },
  errorBadge: {
    position: 'absolute',
    left: -6,
    bottom: -6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.state.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorBadgeText: {
    color: colors.text.inverse,
    fontSize: 10,
    lineHeight: 10,
    fontWeight: typography.weight.bold,
  },
  progressTrack: {
    width: '82%',
    height: 4,
    borderRadius: radius.full,
    backgroundColor: '#e0e0e0',
    overflow: 'hidden',
    marginTop: space[9],
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.full,
    backgroundColor: '#1683ff',
  },
  statusCard: {
    minHeight: 74,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: space[7],
    paddingVertical: space[6],
  },
  statusCardSuccess: {
    borderColor: colors.border.coolActive,
    backgroundColor: '#f7fbff',
  },
  statusCardError: {
    borderColor: '#ff6d6d',
    backgroundColor: colors.surface.white,
  },
  statusContent: {
    flex: 1,
    marginLeft: space[6],
    marginRight: space[5],
  },
  fileName: {
    color: colors.text.coolMuted,
    fontSize: typography.fontSize.xl,
    lineHeight: typography.lineHeight.lg,
    fontWeight: '500',
  },
  fileSize: {
    marginTop: 5,
    color: colors.text.coolSubtle,
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.md,
  },
  errorText: {
    color: colors.state.error,
    fontSize: 18,
    lineHeight: typography.lineHeight.body,
    fontWeight: typography.weight.semibold,
  },
  removeButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonText: {
    color: colors.brand.primary,
    fontSize: 20,
    lineHeight: 20,
    fontWeight: typography.weight.bold,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: space[8],
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border.neutral,
  },
  dividerText: {
    marginHorizontal: space[5],
    color: colors.text.neutralMuted,
    fontSize: typography.fontSize.xl,
    lineHeight: typography.lineHeight.base,
    fontWeight: typography.weight.semibold,
  },
  textareaWrap: {
    minHeight: 164,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border.cool,
    paddingHorizontal: space[6],
    paddingTop: space[5],
    paddingBottom: space[4],
    backgroundColor: colors.surface.white,
  },
  textarea: {
    minHeight: 140,
    color: '#334155',
    fontSize: typography.fontSize.xl,
    lineHeight: typography.lineHeight.body,
    textAlignVertical: 'top',
  },
  editorHint: {
    marginTop: space[4],
    color: '#6f8097',
    fontSize: typography.fontSize.md,
    lineHeight: typography.lineHeight.md,
    fontWeight: '500',
  },
  tipText: {
    color: '#b8b8b8',
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.body,
  },
})
