import {StyleSheet} from 'react-native'
import {
  CARD_HEIGHT,
  CARD_WIDTH,
  INDEX_ITEM_HEIGHT,
  INDEX_LINE_HEIGHT,
  RAIL_BUBBLE_HEIGHT,
  SCORE_PANEL_HEIGHT,
} from './shared'

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: 372,
    alignSelf: 'center',
    position: 'relative',
  },
  stack: {
    width: '100%',
    height: 372,
  },
  cardLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: CARD_HEIGHT,
  },
  groundShadow: {
    position: 'absolute',
    left: 54,
    top: 322,
    width: 198,
    height: 24,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.16)',
  },
  cardBase: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 18},
    shadowOpacity: 0.2,
    shadowRadius: 22,
    elevation: 8,
  },
  cardHandle: {
    position: 'absolute',
    top: 7,
    left: '50%',
    width: 75,
    height: 10,
    marginLeft: -37.5,
    borderRadius: 999,
    backgroundColor: 'rgba(17,24,39,0.88)',
    zIndex: 6,
  },
  createCardLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: CARD_HEIGHT,
    zIndex: 118,
    elevation: 18,
  },
  createCardBase: {
    position: 'absolute',
    left: 10,
    top: -8,
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#1c77eb',
    backgroundColor: '#eaf2ff',
    shadowColor: '#5b7bb2',
    shadowOffset: {width: 0, height: 22},
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 16,
  },
  createCardContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 96,
    paddingBottom: 28,
    justifyContent: 'space-between',
  },
  createCardTitle: {
    color: '#1c77eb',
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '500',
  },
  createCardPromptWrap: {
    width: '100%',
  },
  createCardPromptText: {
    color: 'rgba(24,24,27,0.78)',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    marginBottom: 8,
  },
  createCardPromptAccent: {
    color: '#111111',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  textureLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  textureWrap: {
    ...StyleSheet.absoluteFillObject,
  },
  cardContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 52,
    paddingBottom: 16,
    justifyContent: 'space-between',
  },
  cardContentTop: {
    width: '100%',
  },
  gradeRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 34,
  },
  gradeLetter: {
    fontSize: 58,
    lineHeight: 58,
    fontWeight: '300',
    letterSpacing: -1.6,
  },
  gradeMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
    marginLeft: 6,
    marginBottom: 10,
  },
  gradeMetaDark: {
    color: 'rgba(255,255,255,0.66)',
    textShadowColor: 'rgba(0,0,0,0.22)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 4,
  },
  fieldGroup: {
    marginBottom: 12,
  },
  metaLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    marginBottom: 2,
  },
  metaLabelDark: {
    letterSpacing: 0.2,
    textShadowColor: 'rgba(0,0,0,0.18)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 3,
  },
  cardCompany: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
    letterSpacing: 0,
  },
  cardCompanyDark: {
    fontSize: 18,
    lineHeight: 25,
    fontWeight: '600',
    textShadowColor: 'rgba(0,0,0,0.26)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 6,
  },
  cardLocation: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  cardBodyDark: {
    textShadowColor: 'rgba(0,0,0,0.22)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 5,
  },
  cardRole: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  cardDate: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '400',
  },
  cardDateDark: {
    textShadowColor: 'rgba(0,0,0,0.18)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 4,
  },
  scorePanel: {
    position: 'absolute',
    left: -1,
    right: -1,
    bottom: -1,
    height: SCORE_PANEL_HEIGHT + 1,
    overflow: 'hidden',
    shadowColor: '#1f73e8',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 4,
  },
  scorePanelLayer: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  scorePanelTrack: {
    width: '100%',
    height: '100%',
    borderWidth: 0,
    borderTopWidth: 0,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  scorePanelContent: {
    paddingLeft: 18,
    paddingTop: 8,
    paddingBottom: 8,
    justifyContent: 'flex-start',
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  scoreNumber: {
    color: '#ffffff',
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '300',
    letterSpacing: 1.2,
  },
  scorePercent: {
    color: '#ffffff',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '500',
    marginLeft: 2,
    marginBottom: 6,
  },
  scoreLabel: {
    color: 'rgba(255,255,255,0.95)',
    fontSize: 10,
    lineHeight: 12,
    marginTop: -1,
  },
  logoMarkWrap: {
    position: 'absolute',
  },
  lightBodyScrim: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 186,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  darkPatternBand: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  darkPatternWrap: {
    position: 'absolute',
    left: 20,
    top: 2,
    width: 178,
    height: 306,
    opacity: 0.72,
  },
  darkPatternTopReveal: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 204,
    overflow: 'hidden',
  },
  darkPatternTopRevealPattern: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.98,
  },
  darkPatternBodyDampen: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 202,
  },
  darkContentPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 196,
    overflow: 'hidden',
  },
  darkContentPanelSoftBlur: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 196,
  },
  darkContentPanelSourceMute: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 196,
    backgroundColor: 'rgba(10,12,16,0.06)',
  },
  darkContentPanelTransitionMask: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 160,
    height: 36,
  },
  darkContentPanelMilkVeil: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 196,
  },
  darkContentPanelFogOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 196,
  },
  darkContentPanelSheen: {
    ...StyleSheet.absoluteFillObject,
  },
  darkContentPanelTopEdge: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 188,
    height: 8,
    backgroundColor: 'rgba(8,10,14,0.08)',
  },
  dimOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
  },
  indexRailWrap: {
    position: 'absolute',
    right: -26,
    width: 28,
    alignItems: 'flex-end',
    zIndex: 140,
    elevation: 140,
  },
  guideSvg: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  indexRail: {
    width: 28,
    paddingVertical: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  indexPressable: {
    width: 28,
  },
  indexIndicator: {
    position: 'absolute',
    right: 0,
    width: 7,
    height: INDEX_LINE_HEIGHT,
    borderRadius: 999,
    backgroundColor: '#858f9d',
  },
  indexItem: {
    width: 28,
    height: INDEX_ITEM_HEIGHT,
    paddingRight: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  indexTick: {
    width: 4,
    height: 4,
    borderRadius: 1.5,
    backgroundColor: 'rgba(170,178,191,0.74)',
    marginRight: 4,
  },
  indexTickActive: {
    width: 5,
    height: 5,
    backgroundColor: '#5b6472',
  },
  indexLabelWrap: {
    width: 10,
    alignItems: 'center',
  },
  indexLabel: {
    width: 10,
    textAlign: 'center',
    color: '#b8bec8',
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '500',
  },
  indexLabelActive: {
    color: '#4f5865',
    fontWeight: '700',
  },
  dragBubble: {
    position: 'absolute',
    right: 18,
    width: 30,
    height: RAIL_BUBBLE_HEIGHT,
    borderRadius: 14,
    backgroundColor: '#286fe7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#286fe7',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  dragBubbleText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
})
