import {StyleSheet} from 'react-native'
import {colors, radius, space, typography} from '@/styles/tokens'
import {CARD_HEIGHT, CARD_WIDTH, DETAIL_ITEM_HEIGHT} from './AnalysisStage.constants'

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  overlayGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.36)',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: space[11],
    paddingBottom: 88,
  },
  cardStage: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    marginBottom: 52,
    position: 'relative',
  },
  cardSpinShell: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    overflow: 'visible',
  },
  cardFace: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 18,
    alignItems: 'center',
    paddingTop: space[7],
    backfaceVisibility: 'hidden',
  },
  cardFront: {
    backgroundColor: '#fbf4ef',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.88)',
    shadowColor: '#9d8f86',
  },
  cardBack: {
    backgroundColor: '#1e1b1b',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.94)',
    alignItems: 'stretch',
    overflow: 'hidden',
  },
  cardHardware: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 28,
  },
  cardHardwareCompact: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 28,
  },
  cardHardwareSlot: {
    width: 44,
    height: 5,
    borderRadius: radius.full,
    backgroundColor: 'rgba(248,240,233,0.98)',
  },
  cardHardwareSlotBack: {
    width: 52,
    height: 8,
    backgroundColor: '#9d9998',
  },
  frontBadge: {
    width: 66,
    height: 66,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(232, 224, 217, 0.95)',
    shadowColor: '#d8d2cd',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 36,
  },
  frontBadgeText: {
    color: '#959caf',
    fontSize: typography.fontSize.title + 5,
    lineHeight: typography.lineHeight.badge,
    fontWeight: typography.weight.bold,
  },
  frontPrimaryBar: {
    width: 102,
    height: 16,
    borderRadius: radius.full,
    backgroundColor: 'rgba(235, 231, 228, 0.92)',
    marginBottom: space[5],
  },
  frontSecondaryBar: {
    width: 74,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: 'rgba(232, 228, 225, 0.82)',
  },
  cardBackContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    paddingTop: space[7],
    paddingBottom: space[7],
  },
  backBadgeWrap: {
    width: 66,
    height: 66,
    marginBottom: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBodyBars: {
    width: '100%',
    alignItems: 'center',
  },
  backPrimaryBar: {
    width: 102,
    height: 16,
    borderRadius: radius.full,
    backgroundColor: '#5d5c61',
    marginBottom: space[5],
  },
  backSecondaryBar: {
    width: 74,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: '#67656a',
  },
  copyBlock: {
    width: '100%',
    alignItems: 'center',
  },
  titleRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: space[6],
    paddingHorizontal: space[3],
  },
  titleLead: {
    color: '#ff6230',
    fontSize: 21,
    lineHeight: typography.lineHeight.badge,
    fontWeight: typography.weight.bold,
    marginRight: space[3],
  },
  detailViewport: {
    width: 210,
    height: DETAIL_ITEM_HEIGHT,
    overflow: 'hidden',
    justifyContent: 'center',
    position: 'relative',
  },
  detailTrack: {
    width: '100%',
  },
  detailItem: {
    width: '100%',
    height: DETAIL_ITEM_HEIGHT,
  },
  detailSlide: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: DETAIL_ITEM_HEIGHT,
  },
  titleDetail: {
    width: '100%',
    color: '#696768',
    fontSize: 20,
    lineHeight: DETAIL_ITEM_HEIGHT,
    fontWeight: typography.weight.semibold,
  },
  subtitle: {
    color: '#b1adb0',
    fontSize: 13.5,
    lineHeight: typography.lineHeight.base,
    textAlign: 'center',
  },
  cancelAction: {
    position: 'absolute',
    right: 32,
    bottom: 40,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cancelActionMark: {
    color: '#1f1b1a',
    fontSize: 20,
    lineHeight: typography.lineHeight.xl,
    marginRight: space[2],
  },
  cancelActionText: {
    color: '#1f1b1a',
    fontSize: 15.5,
    lineHeight: typography.lineHeight.xl,
    fontWeight: '500',
  },
})
